### ISSUE TITLE
Неинформативное название переменной

### ISSUE THREAD

**Issue by uzarsalan** [Dorzhieva-Ayana/homework-Ayana_Dorzhieva#9]
Не очень понятное незвание. Старайся давать переменным понятные имена. Исключение составляют переменные i,j,k,l ... которыми обозначают итератор в цикле. При том обычно их по очереди используют для вложенных циклов

https://github.com/Dorzhieva-Ayana/homework-Ayana_Dorzhieva/blob/6d8e4bc1ccb8b58f63f59ccbbd960e856f6eedf9/Js%208%20cycles/script.js#L58

**Comment by Dorzhieva-Ayana** [comment]
хорошо, спасибо. Исправила название.
https://github.com/Dorzhieva-Ayana/homework-Ayana_Dorzhieva/commit/1a01c7cc614549688705ba87217c5cb76ef3d83e
